// Generated by scripts/optimize-service-images.mjs. Keep original PNGs as source assets.
import image0_webp_320 from '../../assets/servicescards/optimized/banner-itr-new-320.webp';
import image0_webp_640 from '../../assets/servicescards/optimized/banner-itr-new-640.webp';
import image0_webp_1280 from '../../assets/servicescards/optimized/banner-itr-new-1280.webp';
import image0_avif_320 from '../../assets/servicescards/optimized/banner-itr-new-320.avif';
import image0_avif_640 from '../../assets/servicescards/optimized/banner-itr-new-640.avif';
import image0_avif_1280 from '../../assets/servicescards/optimized/banner-itr-new-1280.avif';
import image1_webp_320 from '../../assets/servicescards/optimized/banner-pan-update-320.webp';
import image1_webp_640 from '../../assets/servicescards/optimized/banner-pan-update-640.webp';
import image1_webp_1280 from '../../assets/servicescards/optimized/banner-pan-update-1280.webp';
import image1_avif_320 from '../../assets/servicescards/optimized/banner-pan-update-320.avif';
import image1_avif_640 from '../../assets/servicescards/optimized/banner-pan-update-640.avif';
import image1_avif_1280 from '../../assets/servicescards/optimized/banner-pan-update-1280.avif';
import image2_webp_320 from '../../assets/servicescards/optimized/banner-car-new-320.webp';
import image2_webp_640 from '../../assets/servicescards/optimized/banner-car-new-640.webp';
import image2_webp_1280 from '../../assets/servicescards/optimized/banner-car-new-1280.webp';
import image2_avif_320 from '../../assets/servicescards/optimized/banner-car-new-320.avif';
import image2_avif_640 from '../../assets/servicescards/optimized/banner-car-new-640.avif';
import image2_avif_1280 from '../../assets/servicescards/optimized/banner-car-new-1280.avif';
import image3_webp_320 from '../../assets/servicescards/optimized/banner-pan-service-320.webp';
import image3_webp_640 from '../../assets/servicescards/optimized/banner-pan-service-640.webp';
import image3_webp_1280 from '../../assets/servicescards/optimized/banner-pan-service-1280.webp';
import image3_avif_320 from '../../assets/servicescards/optimized/banner-pan-service-320.avif';
import image3_avif_640 from '../../assets/servicescards/optimized/banner-pan-service-640.avif';
import image3_avif_1280 from '../../assets/servicescards/optimized/banner-pan-service-1280.avif';
import image4_webp_320 from '../../assets/servicescards/optimized/banner-bike-new-320.webp';
import image4_webp_640 from '../../assets/servicescards/optimized/banner-bike-new-640.webp';
import image4_webp_1280 from '../../assets/servicescards/optimized/banner-bike-new-1280.webp';
import image4_avif_320 from '../../assets/servicescards/optimized/banner-bike-new-320.avif';
import image4_avif_640 from '../../assets/servicescards/optimized/banner-bike-new-640.avif';
import image4_avif_1280 from '../../assets/servicescards/optimized/banner-bike-new-1280.avif';
import image5_webp_320 from '../../assets/servicescards/optimized/banner-health-new-320.webp';
import image5_webp_640 from '../../assets/servicescards/optimized/banner-health-new-640.webp';
import image5_webp_1280 from '../../assets/servicescards/optimized/banner-health-new-1280.webp';
import image5_avif_320 from '../../assets/servicescards/optimized/banner-health-new-320.avif';
import image5_avif_640 from '../../assets/servicescards/optimized/banner-health-new-640.avif';
import image5_avif_1280 from '../../assets/servicescards/optimized/banner-health-new-1280.avif';
import image6_webp_320 from '../../assets/servicescards/optimized/banner-car-offer-320.webp';
import image6_webp_640 from '../../assets/servicescards/optimized/banner-car-offer-640.webp';
import image6_webp_1280 from '../../assets/servicescards/optimized/banner-car-offer-1280.webp';
import image6_avif_320 from '../../assets/servicescards/optimized/banner-car-offer-320.avif';
import image6_avif_640 from '../../assets/servicescards/optimized/banner-car-offer-640.avif';
import image6_avif_1280 from '../../assets/servicescards/optimized/banner-car-offer-1280.avif';
export const serviceImageSources: Record<string, {webp: string; avif: string}> = {
[image0_webp_1280]: { webp: [image0_webp_320 + ' 320w', image0_webp_640 + ' 640w', image0_webp_1280 + ' 1024w'].join(', '), avif: [image0_avif_320 + ' 320w', image0_avif_640 + ' 640w', image0_avif_1280 + ' 1024w'].join(', ') },
[image1_webp_1280]: { webp: [image1_webp_320 + ' 320w', image1_webp_640 + ' 640w', image1_webp_1280 + ' 1024w'].join(', '), avif: [image1_avif_320 + ' 320w', image1_avif_640 + ' 640w', image1_avif_1280 + ' 1024w'].join(', ') },
[image2_webp_1280]: { webp: [image2_webp_320 + ' 320w', image2_webp_640 + ' 640w', image2_webp_1280 + ' 1024w'].join(', '), avif: [image2_avif_320 + ' 320w', image2_avif_640 + ' 640w', image2_avif_1280 + ' 1024w'].join(', ') },
[image3_webp_1280]: { webp: [image3_webp_320 + ' 320w', image3_webp_640 + ' 640w', image3_webp_1280 + ' 1024w'].join(', '), avif: [image3_avif_320 + ' 320w', image3_avif_640 + ' 640w', image3_avif_1280 + ' 1024w'].join(', ') },
[image4_webp_1280]: { webp: [image4_webp_320 + ' 320w', image4_webp_640 + ' 640w', image4_webp_1280 + ' 1024w'].join(', '), avif: [image4_avif_320 + ' 320w', image4_avif_640 + ' 640w', image4_avif_1280 + ' 1024w'].join(', ') },
[image5_webp_1280]: { webp: [image5_webp_320 + ' 320w', image5_webp_640 + ' 640w', image5_webp_1280 + ' 1024w'].join(', '), avif: [image5_avif_320 + ' 320w', image5_avif_640 + ' 640w', image5_avif_1280 + ' 1024w'].join(', ') },
[image6_webp_1280]: { webp: [image6_webp_320 + ' 320w', image6_webp_640 + ' 640w', image6_webp_1280 + ' 1024w'].join(', '), avif: [image6_avif_320 + ' 320w', image6_avif_640 + ' 640w', image6_avif_1280 + ' 1024w'].join(', ') }
};
