// src/api/endpoints.js
// Complete backend route map for Reward Planners Backend

export const API_BASE_URL = 'https://rewardplanners.com/api/crm';
export const IMAGE_BASE_URL = import.meta.env.VITE_IMAGE_URL || 'https://cdn.rewardplanners.com';

export const ENDPOINTS = {
  auth: {
    login: '/v1/auth/login',
    register: '/v1/auth/register',
    refresh: '/v1/auth/refresh',
    userInfo: '/v1/auth/user-info',
    profile: '/v1/auth/profile',
    changePassword: '/v1/auth/change-password',
    activateAccount: '/v1/auth/activate-account',
    verifyActivationOtp: '/v1/auth/verify-activation-otp',
    setPassword: '/v1/auth/set-password',
    forgotPassword: '/v1/auth/forgot-password',
    verifyForgotPasswordOtp: '/v1/auth/verify-forgot-password-otp',
    resetPassword: '/v1/auth/reset-password',
    addresses: '/v1/auth/addresses',
    address: '/v1/auth/address',
    addressById: (id) => `/v1/auth/address/${id}`,
    countries: '/v1/auth/countries',
    states: (countryId) => `/v1/auth/states/${countryId}`,
  },
  terms: {
    status: '/v1/terms/status',
    accept: '/v1/terms/accept',
  },
  global: {
    suggestions: '/v1/global/search/suggestions',
  },
  products: {
    all: '/v1/product/all-products',
    categories: '/v1/product/categories',
    categoriesWithSub: '/v1/product/categories-with-subcategories',
    details: (id) => `/v1/product/product-details/${id}`,
    byCategory: (catId) => `/v1/product/by-category/${catId}`,
    bySubcategory: (subId) => `/v1/product/by-subcategory/${subId}`,
    similar: (id) => `/v1/product/similar/${id}`,
    bestSellers: '/v1/product/best-sellers',
    trending: '/v1/product/trending',
    topRated: '/v1/product/top-rated',
    newArrivals: '/v1/product/new-arrivals',
    customersAlsoBought: (id) => `/v1/product/${id}/customers-also-bought`,
    searchSuggestions: '/v1/product/search/suggestions',
    searchProducts: '/v1/product/search/products',
    searchHistory: '/v1/product/search/history',
  },
  cart: {
    items: '/v1/cart/cart-items',
    item: '/v1/cart/cart-item',
    summary: '/v1/cart/cart-summary',
    checkStock: (variantId) => `/v1/cart/cart-items/check-stock/${variantId}`,
    updateItem: (id) => `/v1/cart/cart-items/${id}`,
    deleteItem: (id) => `/v1/cart/cart-items/${id}`,
  },
  checkout: {
    getCart: '/v1/checkout/get-cart',
    cart: '/v1/checkout/cart',
    getBuyNow: '/v1/checkout/get-buy-now',
    buyNow: '/v1/checkout/buy-now',
    receipt: (orderId) => `/v1/checkout/order-receipt/${orderId}`,
  },
  payment: {
    createOrder: '/v1/payment/create-order',
    verifyPayment: '/v1/payment/verify-payment',
    paymentStatus: (orderId) => `/v1/payment/payment-status/${orderId}`,
    cancelOrder: (orderId) => `/v1/payment/cancel-order/${orderId}`,
  },
  orders: {
    ordersHistory: '/v1/orders/orders-history',
    myOrders: '/v1/orders/orders-history',
    details: (orderId) => `/v1/orders/order-details/${orderId}`,
    receipt: (orderId) => `/v1/checkout/order-receipt/${orderId}`,
    invoice: (orderId) => `/v1/orders/invoice/${orderId}`,
    cancel: (orderId) => `/v1/orders/cancel/${orderId}`,
    cancellationReasons: '/v1/orders/cancellation-reasons',
  },
  logistics: {
    checkServiceability: '/v1/logistics/check-serviceability',
    trackStatus: (orderId) => `/v1/logistics/track-status/${orderId}`,
  },
  services: {
    categories: '/v1/category/all-categories',
    allServices: '/v1/service/all-services',
    byCategory: (categoryId) => `/v1/service/by-category/${categoryId}`,
    details: (id) => `/v1/service/details/${id}`,
    bundles: '/v1/service-bundle',
    bundleDetail: (id) => `/v1/service-bundle/bundle-detail/${id}`,
    banners: '/v1/service-banner',
    cart: '/v1/service-cart',
    checkout: '/v1/service-checkout',
    orders: '/v1/service-orders',
    enquiry: '/v1/service-enquiry',
    form: (id) => `/v1/service-form/${id}`,
    documentUpload: '/v1/service-document/upload',
    mfTree: (categoryId = 4) => `/v1/mutual-fund/category-tree/${categoryId}`,
  },
  bbps: {
    categories: '/v1/bills/categories',
    locations: '/v1/bills/locations',
    operators: '/v1/bills/operators',
    operatorDetails: (id) => `/v1/bills/operator/${id}`,
    fetchBill: '/v1/bills/fetch-bill',
    createOrder: '/v1/bill-pay/create-order',
    verify: '/v1/bill-pay/verify',
  },
  fitness: {
    summary: '/v1/dashboard/summary',
    weekly: '/v1/progress/weekly',
    stats: '/v1/stats/month',
    achievements: '/v1/achievement/list',
    statement: '/v1/wallet/statement',
  },
  insurance: {
    gmc: '/v1/gmc/dashboard',
    claims: '/v1/claims',
  },
};
