// src/api/endpoints.js
// Complete backend route map for Reward Planners Backend
type ApiId = string | number;

export const API_BASE_URL = import.meta.env.VITE_API_URL || 'https://rewardplanners.com/api/crm';
export const IMAGE_BASE_URL = import.meta.env.VITE_IMAGE_URL || 'https://cdn.rewardplanners.com';

export const ENDPOINTS = {
  auth: {
    login: '/v1/auth/login',
    register: '/v1/auth/register',
    refresh: '/v1/auth/refresh',
    userInfo: '/v1/auth/user-info',
    profile: '/v1/auth/profile',
    changePassword: '/v1/auth/change-password',
    activateAccount: '/v1/auth/activate-account',
    verifyActivationOtp: '/v1/auth/verify-activation-otp',
    setPassword: '/v1/auth/set-password',
    forgotPassword: '/v1/auth/forgot-password',
    verifyForgotPasswordOtp: '/v1/auth/verify-forgot-password-otp',
    resetPassword: '/v1/auth/reset-password',
    addresses: '/v1/auth/addresses',
    address: '/v1/auth/address',
    addressById: (id: ApiId) => `/v1/auth/address/${id}`,
    countries: '/v1/auth/countries',
    states: (countryId: ApiId) => `/v1/auth/states/${countryId}`,
  },
  terms: {
    status: '/v1/terms/status',
    accept: '/v1/terms/accept',
  },
  global: {
    suggestions: '/v1/global/search/suggestions',
  },
  products: {
    all: '/v1/product/all-products',
    categories: '/v1/product/categories',
    categoriesWithSub: '/v1/product/categories-with-subcategories',
    details: (id: ApiId) => `/v1/product/product-details/${id}`,
    byCategory: (catId: ApiId) => `/v1/product/by-category/${catId}`,
    bySubcategory: (subId: ApiId) => `/v1/product/by-subcategory/${subId}`,
    similar: (id: ApiId) => `/v1/product/similar/${id}`,
    bestSellers: '/v1/product/best-sellers',
    trending: '/v1/product/trending',
    topRated: '/v1/product/top-rated',
    newArrivals: '/v1/product/new-arrivals',
    mostViewed: '/v1/product/most-viewed',
    recentProducts: '/v1/product/recent-products',
    recommendations: '/v1/product/recommendations',
    customersAlsoBought: (id: ApiId) => `/v1/product/${id}/customers-also-bought`,
    searchSuggestions: '/v1/product/search/suggestions',
    searchProducts: '/v1/product/search/products',
    searchHistory: '/v1/product/search/history',
  },
  cart: {
    items: '/v1/cart/cart-items',
    item: '/v1/cart/cart-item',
    summary: '/v1/cart/cart-summary',
    checkStock: (variantId: ApiId) => `/v1/cart/cart-items/check-stock/${variantId}`,
    updateItem: (id: ApiId) => `/v1/cart/cart-items/${id}`,
    deleteItem: (id: ApiId) => `/v1/cart/cart-items/${id}`,
  },
  checkout: {
    getCart: '/v1/checkout/get-cart',
    cart: '/v1/checkout/cart',
    getBuyNow: '/v1/checkout/get-buy-now',
    buyNow: '/v1/checkout/buy-now',
    receipt: (orderId: ApiId) => `/v1/checkout/order-receipt/${orderId}`,
  },
  payment: {
    createOrder: '/v1/payment/create-order',
    verifyPayment: '/v1/payment/verify-payment',
    paymentStatus: (orderId: ApiId) => `/v1/payment/payment-status/${orderId}`,
    cancelOrder: (orderId: ApiId) => `/v1/payment/cancel-order/${orderId}`,
  },
  orders: {
    ordersHistory: '/v1/orders/orders-history',
    myOrders: '/v1/orders/orders-history',
    details: (orderId: ApiId) => `/v1/orders/order-details/${orderId}`,
    receipt: (orderId: ApiId) => `/v1/checkout/order-receipt/${orderId}`,
    invoice: (orderId: ApiId) => `/v1/orders/invoice/${orderId}`,
    cancel: (orderId: ApiId) => `/v1/orders/cancel/${orderId}`,
    cancellationReasons: '/v1/orders/cancellation-reasons',
  },
  logistics: {
    checkServiceability: '/v1/logistics/check-serviceability',
    trackStatus: (orderId: ApiId) => `/v1/logistics/track-status/${orderId}`,
  },
  services: {
    categories: '/v1/category/all-categories',
    categoryById: (id: ApiId) => `/v1/category/find/${id}`,
    allServices: '/v1/service/all-services',
    byCategory: (categoryId: ApiId) => `/v1/service/by-category/${categoryId}`,
    details: (id: ApiId) => `/v1/service/details/${id}`,
    serviceById: (id: ApiId) => `/v1/service/find/${id}`,
    searchSuggestions: '/v1/service/search/suggestions',
    searchHistory: '/v1/service/search/history',
    feedback: '/v1/service/feedback',
    homeSections: '/v1/service/home',
    related: (serviceId: ApiId) => `/v1/service/related/${serviceId}`,
    topPicks: '/v1/service/top-picks',
    valueAdded: (serviceId: ApiId) => `/v1/service/value-added/${serviceId}`,
    bundles: '/v1/service-bundle',
    bundleDetail: (id: ApiId) => `/v1/service-bundle/bundle-detail/${id}`,
    banners: '/v1/service-banner',
    cart: '/v1/service-cart',
    checkout: '/v1/service-checkout',
    orders: '/v1/service-orders',
    enquiry: '/v1/service-enquiry',
    form: (id: ApiId) => `/v1/service-form/form/${id}`,
    variants: (serviceId: ApiId) => `/v1/service-variant/find/${serviceId}`,
    variantSection: (variantId: ApiId) => `/v1/service-variant/variant-section/${variantId}`,
    documents: (serviceId: ApiId) => `/v1/service-document/find/${serviceId}`,
    documentUpload: '/v1/service-document/upload',
    insurance: {
      start: '/v1/insurance/start',
      saveStep: '/v1/insurance/save-step',
      getQuotes: '/v1/insurance/get-quotes',
      get: (id: ApiId) => `/v1/insurance/${id}`,
      complete: '/v1/insurance/complete',
      selectPlan: '/v1/insurance/select-plan',
    },
    serviceOrders: {
      createOrder: '/v1/service-orders/create-order',
      verifyPayment: '/v1/service-orders/verify-payment',
      paymentStatus: (parentOrderId: ApiId) => `/v1/service-orders/payment-status/${parentOrderId}`,
      myOrders: '/v1/service-orders/my-orders',
      orderDetails: (parentOrderId: ApiId) => `/v1/service-orders/order-details/${parentOrderId}`,
      invoiceDetails: (parentId: ApiId) => `/v1/service-orders/invoice-details/${parentId}`,
      submitDocuments: (parentOrderId: ApiId) => `/v1/service-orders/submit-documents/${parentOrderId}`,
      cancellationReasons: '/v1/service-orders/cancellation-reasons',
      cancelOrderRequest: '/v1/service-orders/cancel-order-request',
      cancellationDetails: (serviceOrderId: ApiId) => `/v1/service-orders/cancellation-details/${serviceOrderId}`,
      issueTypes: '/v1/service-orders/issue-types',
      orderHelp: '/v1/service-orders/order-help',
      supportRequests: (serviceOrderId: ApiId) => `/v1/service-orders/order-help/${serviceOrderId}`,
      orderDocuments: (orderId: ApiId) => `/v1/service-order-documents/documents/${orderId}`,
      parentDocuments: (parentOrderId: ApiId) => `/v1/service-order-documents/parent-documents/${parentOrderId}`,
    },
    mfTree: (categoryId = 4) => `/v1/mutual-fund/category-tree/${categoryId}`,
    mfSectionContent: (id: ApiId) => `/v1/mutual-fund/section-content/${id}`,
    mfArticle: (id: ApiId) => `/v1/mutual-fund/find/${id}`,
  },
  bbps: {
    categories: '/v1/bills/categories',
    locations: '/v1/bills/locations',
    operators: '/v1/bills/operators',
    searchOperators: '/v1/bills/operators/search',
    groupedOperators: '/v1/bills/operators-grouped',
    operatorDetails: (id: ApiId) => `/v1/bills/operator/${id}`,
    rechargePlans: '/v1/bills/recharge/plans',
    fetchBill: '/v1/bills/fetch-bill',
    createOrder: '/v1/bill-pay/create-order',
    verifyPayment: '/v1/bill-pay/verify-payment',
    checkStatus: (transactionId: ApiId) => `/v1/bills/check-status/${transactionId}`,
    cancelOrder: '/v1/bill-pay/cancel-order',
    orderHistory: '/v1/bills/order-history',
  },
  fitness: {
    summary: '/v1/dashboard/summary',
    weekly: '/v1/progress/weekly',
    stats: '/v1/stats/month',
    achievements: '/v1/achievement/list',
    statement: '/v1/wallet/statement',
  },
  insurance: {
    gmc: '/v1/gmc/dashboard',
    claims: '/v1/claims',
  },
  support: {
    categories: '/v1/support/categories',
    createTicket: '/v1/support/create-ticket',
    myTickets: '/v1/support/my-tickets',
    recentOrders: '/v1/support/recent-orders',
  },
  todo: {
    list: '/v1/todo',
    create: '/v1/todo',
    update: (id: string | number) => `/v1/todo/${id}`,
    complete: (id: string | number) => `/v1/todo/${id}/complete`,
    completeMultiple: '/v1/todo/complete/multiple',
    updateReminder: (id: string | number) => `/v1/todo/${id}/reminder`,
    delete: (id: string | number) => `/v1/todo/${id}`,
    deleteMultiple: '/v1/todo/delete/multiple',
  },
  notification: {
    myNotifications: '/v1/notification/my-notification',
    badge: '/v1/notification/notification-badge',
    markRead: (id: string | number) => `/v1/notification/read/${id}`,
    markAllRead: '/v1/notification/read-all',
    delete: (id: string | number) => `/v1/notification/${id}`,
  },
};

