import { useRef } from 'react';
import ChevronLeft from '@mui/icons-material/ChevronLeft';
import ChevronRight from '@mui/icons-material/ChevronRight';
import type { MFArticleSummary, MFChildCategory } from '../../../../api/mutualFundApi';
import ArticleCard from './ArticleCard';
export default function ArticleRow({ section, articles, description, onSection, onArticle }: { section: MFChildCategory; articles: MFArticleSummary[]; description: string; onSection: (section: MFChildCategory) => void; onArticle: (article: MFArticleSummary) => void }) {
  const rail = useRef<HTMLDivElement>(null);
  return <section className="mf-learning-section rounded-[2rem] px-5 py-8 sm:px-8 sm:py-10"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div className="max-w-4xl"><h2 className="text-2xl font-semibold leading-snug sm:text-3xl">{section.title}</h2><p className="mf-muted mt-4 text-sm leading-7 sm:text-base">{description}</p></div><div className="flex items-center gap-2"><button onClick={() => onSection(section)} className="mf-accent mr-2 text-sm font-semibold hover:underline">Browse topics</button>{articles.length > 0 && <><button aria-label={`Scroll ${section.title} left`} onClick={() => rail.current?.scrollBy({ left: -360, behavior: 'smooth' })} className="mf-panel mf-accent rounded-full border p-2 shadow-sm"><ChevronLeft sx={{ fontSize: 20 }} /></button><button aria-label={`Scroll ${section.title} right`} onClick={() => rail.current?.scrollBy({ left: 360, behavior: 'smooth' })} className="mf-panel mf-accent rounded-full border p-2 shadow-sm"><ChevronRight sx={{ fontSize: 20 }} /></button></>}</div></div>{articles.length ? <div ref={rail} className="flex snap-x snap-mandatory gap-5 overflow-x-auto pb-5 sm:gap-6">{articles.map(article => <div key={article.id} className="w-[85%] max-w-[360px] shrink-0 snap-start sm:w-[calc((100%-1.5rem)/2)] lg:w-[calc((100%-3rem)/3)]"><ArticleCard article={article} onOpen={onArticle} /></div>)}</div> : <p className="mf-muted py-6">No articles have been published in this section yet.</p>}</section>;
}
